org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.0
forge_version_range=[52.1,)
loader_version_range=[52,)

mapping_channel=official
mapping_version=1.21.1

mod_id=shadowservants
mod_name=Shadow Servants
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.shadowservants
mod_authors=Shadow Servants
mod_description=Transforme criaturas derrotadas em servos das sombras. Colete progresso, invoque, guarde e controle seus servos.
